In [2]:
import numpy as np

In [3]:
h = 1.0
csuh = 3.0
vol1 = np.sqrt(0.75)
a = np.array([[1.,0.,0.],[-0.5,np.sqrt(3)/2,0.],[0.0,0.0,csuh]])*h
vol = lambda at: at[0].dot(np.cross(at[1],at[2])) 
perm = lambda i: [(i+_)%3 for _ in (0,1,2)]
bl = lambda lat,i,: 2.0 * np.pi /vol(lat) * np.cross(lat[perm(i)[1]],lat[perm(i)[2]])  
b = np.array([bl(a,i) for i in (0,1,2)])
b/2/np.pi*h,vol(a)/vol1


(array([[ 1.        ,  0.57735027, -0.        ],
        [ 0.        ,  1.15470054,  0.        ],
        [ 0.        , -0.        ,  0.33333333]]),
 3.0000000000000004)

In [13]:
t = h/np.sqrt(3) 
vv = np.array([0.,0.,csuh/3.0]) * h 
tv = np.array([[np.sqrt(3)/2,-0.5, 0],[0.0,1.0,0.0],[-np.sqrt(3)/2,-0.5,0.0]]) * t 
ar = np.array([_ + vv for _ in tv])
br = np.array([bl(ar,i) for i in (0,1,2)])
[np.round(br.dot(_)/np.pi/2,8) for _ in a],[np.round(ar.dot(_)/np.pi/2,8) for _ in b],np.round(ar.dot(b[0]+b[1])/np.pi/2,8)


([array([ 1.,  0., -1.]), array([-1.,  1.,  0.]), array([1., 1., 1.])],
 [array([ 0.33333333,  0.33333333, -0.66666667]),
  array([-0.33333333,  0.66666667, -0.33333333]),
  array([0.33333333, 0.33333333, 0.33333333])],
 array([-0.,  1., -1.]))

In [5]:
0.857/0.514807/np.sqrt(3) * 3 

2.8833476275313425

In [6]:
v = (b[0]+b[1])/2/np.pi*h/3
v, np.sqrt(v.dot(v))

(array([0.33333333, 0.57735027, 0.        ]), 0.6666666666666667)

In [7]:
b/2/np.pi

array([[ 1.        ,  0.57735027, -0.        ],
       [ 0.        ,  1.15470054,  0.        ],
       [ 0.        , -0.        ,  0.33333333]])

In [8]:
0.656 * 0.8920604708423396 

0.5851916688725748

In [9]:
b/2/np.pi*h

array([[ 1.        ,  0.57735027, -0.        ],
       [ 0.        ,  1.15470054,  0.        ],
       [ 0.        , -0.        ,  0.33333333]])

In [18]:
br

array([[ 6.28318531, -3.62759873,  2.0943951 ],
       [ 0.        ,  7.25519746,  2.0943951 ],
       [-6.28318531, -3.62759873,  2.0943951 ]])

In [11]:
b[0]/2/np.pi*h,b[1]/2/np.pi*h 

(array([ 1.        ,  0.57735027, -0.        ]),
 array([0.        , 1.15470054, 0.        ]))

In [12]:
np.sqrt(b[0].dot(b[0]))/2/np.pi*h *(np.sqrt(3)/2)

0.9999999999999999

In [14]:
br/2/np.pi*np.sqrt(ar[0].dot(ar[0]))

array([[ 1.15470054, -0.66666667,  0.38490018],
       [ 0.        ,  1.33333333,  0.38490018],
       [-1.15470054, -0.66666667,  0.38490018]])

In [16]:
b/2/np.pi

array([[ 1.        ,  0.57735027, -0.        ],
       [ 0.        ,  1.15470054,  0.        ],
       [ 0.        , -0.        ,  0.33333333]])

In [17]:
b[0]/2/np.pi*np.sqrt(ar[0].dot(ar[0]))

array([ 1.15470054,  0.66666667, -0.        ])